import { useState } from 'react'
import { Link } from 'react-router-dom'
import TimeFilter from '../ui/TimeFilter'
import LeaderboardChart from '../ui/LeaderboardChart'
import SectionLabel from '../ui/SectionLabel'
import { ventureRevenueData, TimePeriod } from '../../data/ventureRevenueData'

/**
 * LeaderboardPage Component
 * BEM Structure: leaderboard-page (block)
 * Elements: leaderboard-page__container, leaderboard-page__header, leaderboard-page__back-button,
 *           leaderboard-page__title, leaderboard-page__description, leaderboard-page__filter-section,
 *           leaderboard-page__chart-section
 */
export default function LeaderboardPage() {
  const [selectedPeriod, setSelectedPeriod] = useState<TimePeriod>('lifetime')

  return (
    <div className="leaderboard-page min-h-screen bg-apollo-dark text-white py-12 px-6">
      <div className="leaderboard-page__container max-w-7xl mx-auto">
        {/* Header */}
        <div className="leaderboard-page__header mb-12">
          {/* Back Button */}
          <Link
            to="/"
            className="leaderboard-page__back-button inline-flex items-center gap-2 text-apollo-blue hover:text-white transition-colors mb-6"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            <span className="font-medium">Back to Home</span>
          </Link>

          <SectionLabel text="VENTURE REVENUE" />

          <h1 className="leaderboard-page__title mt-6 text-section font-normal leading-tight">
            Revenue <span className="text-apollo-blue">Leaderboard</span>
          </h1>

          <p className="leaderboard-page__description mt-4 text-lg text-apollo-text-secondary max-w-3xl">
            Track the performance of Apollo's ventures across our entrepreneurial ecosystem.
            Each venture is run by dedicated team members who drive innovation and growth.
            Revenue figures reflect the total income generated by each business.
          </p>
        </div>

        {/* Time Filter Section */}
        <div className="leaderboard-page__filter-section mb-10">
          <TimeFilter
            selectedPeriod={selectedPeriod}
            onPeriodChange={setSelectedPeriod}
          />
        </div>

        {/* Chart Section */}
        <div className="leaderboard-page__chart-section">
          <LeaderboardChart data={ventureRevenueData[selectedPeriod] || []} />
        </div>

        {/* Footer Note */}
        <div className="mt-12 text-center text-apollo-text-tertiary text-sm">
          <p>Revenue figures are based on actual P&L statements from 2024-2025.</p>
          <p className="mt-2">Team members listed under each venture are the primary contributors and operators.</p>
          <p className="mt-2">Note: Some ventures may show negative cash flow but hold valuable assets (e.g., inventory, equipment).</p>
        </div>
      </div>
    </div>
  )
}
